### 统计分析查询接口
### http://10.6.121.29:8080/sddp/api/v1/event/statistic/statistic/query
### entranceType: 0-安检站，1-安检通道
### statisticType：0-天，1-天/周，2-月，3-月/年
### needSubTime：0-不包含，1-包含；例：统计周期为天，并且包含子时间查询，返回数据粒度要15分钟一条，否则为一天一条

### 查询通道分/天统计数据
POST http://10.6.121.29:8080/sddp/api/v1/event/statistic/statistic/query
Content-Type: application/json
Token: ECACAAAQAABaEAi5NzeX0u2i3sVNM1cKraVApw1yKj9n0TCRGiKu9IIwehAHXOPA+OaPS+AqqaGhYk4wdyJGiwWj2T5f0aEor/chssf6fpNaNANUqv7zQjE1OTM2NjE2MzcyMjE=

{
  "startTime": "2020-06-28T00:00:00.000Z",
  "endTime": "2020-09-02T00:00:00.000Z",
  "entranceList": [
    "8946d6a8e49f4af7bdf0416f9a055e64"
  ],
  "entranceType": 1,
  "eventType": "266241",
  "statisticType": 0,
  "needSubTime": 1,
  "pageNum": 1,
  "pageSize": 20

}

### 查询通道天/周统计数据
POST http://10.6.121.29:8080/sddp/api/v1/event/statistic/statistic/query
Content-Type: application/json
Token: ECACAAAQAABaEAi5NzeX0u2i3sVNM1cKraVApw1yKj9n0TCRGiKu9IIwehAHXOPA+OaPS+AqqaGhYk4wdyJGiwWj2T5f0aEor/chssf6fpNaNANUqv7zQjE1OTM2NjE2MzcyMjE=

{
  "startTime": "2020-07-02T00:00:00.000Z",
  "endTime": "2020-09-02T00:00:00.000Z",
  "entranceList": [
    "8946d6a8e49f4af7bdf0416f9a055e64"
  ],
  "entranceType": 1,
  "eventType": "266241",
  "statisticType": 1,
  "needSubTime": 1,
  "pageNum": 1,
  "pageSize": 20

}

### 查询通道月/年统计数据
POST http://10.6.121.29:8080/sddp/api/v1/event/statistic/statistic/query
Content-Type: application/json
Token: ECACAAAQAABaEAi5NzeX0u2i3sVNM1cKraVApw1yKj9n0TCRGiKu9IIwehAHXOPA+OaPS+AqqaGhYk4wdyJGiwWj2T5f0aEor/chssf6fpNaNANUqv7zQjE1OTM2NjE2MzcyMjE=

{
  "startTime": "2020-05-28T00:00:00.000Z",
  "endTime": "2020-11-02T00:00:00.000Z",
  "entranceList": [
    "8946d6a8e49f4af7bdf0416f9a055e64"
  ],
  "entranceType": 1,
  "eventType": "266241",
  "statisticType": 3,
  "needSubTime": 1,
  "pageNum": 1,
  "pageSize": 20

}

### 查询站点分/天统计接口
POST http://10.6.121.29:8080/sddp/api/v1/event/statistic/statistic/query
Content-Type: application/json
Token: ECACAAAQAABaEAi5NzeX0u2i3sVNM1cKraVApw1yKj9n0TCRGiKu9IIwehAHXOPA+OaPS+AqqaGhYk4wdyJGiwWj2T5f0aEor/chssf6fpNaNANUqv7zQjE1OTM2NjE2MzcyMjE=

{
  "startTime": "2020-07-01T00:00:00.000Z",
  "endTime": "2020-08-01T00:00:00.000Z",
  "entranceList": [
    "1bd4efb614f44754bbeb654e369fbe05"
  ],
  "entranceType": 0,
  "eventType": "266241",
  "statisticType": 0,
  "needSubTime": 1,
  "pageNum": 1,
  "pageSize": 20

}

### 查询站点天/周统计接口
POST http://10.6.121.29:8080/sddp/api/v1/event/statistic/statistic/query
Content-Type: application/json
Token: ECACAAAQAABaEAi5NzeX0u2i3sVNM1cKraVApw1yKj9n0TCRGiKu9IIwehAHXOPA+OaPS+AqqaGhYk4wdyJGiwWj2T5f0aEor/chssf6fpNaNANUqv7zQjE1OTM2NjE2MzcyMjE=

{
  "startTime": "2020-07-01T00:00:00.000Z",
  "endTime": "2020-08-01T00:00:00.000Z",
  "entranceList": [
    "1bd4efb614f44754bbeb654e369fbe05"
  ],
  "entranceType": 0,
  "eventType": "266241",
  "statisticType": 1,
  "needSubTime": 1,
  "pageNum": 1,
  "pageSize": 20

}

### 查询站点月统计接口
POST http://10.6.121.29:8080/sddp/api/v1/event/statistic/statistic/query
Content-Type: application/json
Token: ECACAAAQAABaEAi5NzeX0u2i3sVNM1cKraVApw1yKj9n0TCRGiKu9IIwehAHXOPA+OaPS+AqqaGhYk4wdyJGiwWj2T5f0aEor/chssf6fpNaNANUqv7zQjE1OTM2NjE2MzcyMjE=

{
  "startTime": "2020-05-01T00:00:00.000Z",
  "endTime": "2020-08-01T00:00:00.000Z",
  "entranceList": [
    "1bd4efb614f44754bbeb654e369fbe05"
  ],
  "entranceType": 0,
  "eventType": "266241",
  "statisticType": 3,
  "needSubTime": 1,
  "pageNum": 1,
  "pageSize": 20

}

### 266242
### 查询通道分/天统计数据
### 8946d6a8e49f4af7bdf0416f9a055e64 3 通道
### f5c5d45473d7476ab4b6ac7bd9b2ed64 9 通道
POST http://10.6.121.29:8080/sddp/api/v1/event/statistic/statistic/query
Content-Type: application/json
Token: ECACAAAQAABaEAi5NzeX0u2i3sVNM1cKraVApw1yKj9n0TCRGiKu9IIwehAHXOPA+OaPS+AqqaGhYk4wdyJGiwWj2T5f0aEor/chssf6fpNaNANUqv7zQjE1OTM2NjE2MzcyMjE=

{
  "startTime": "2020-07-03T00:00:00.000Z",
  "endTime": "2020-07-04T00:00:00.000Z",
  "entranceList": [
    "f5c5d45473d7476ab4b6ac7bd9b2ed64"
  ],
  "entranceType": 1,
  "eventType": "266242",
  "statisticType": 0,
  "needSubTime": 1,
  "pageNum": 1,
  "pageSize": 20

}

### 查询通道天/周统计数据
POST http://10.6.121.29:8080/sddp/api/v1/event/statistic/statistic/query
Content-Type: application/json
Token: ECACAAAQAABaEAi5NzeX0u2i3sVNM1cKraVApw1yKj9n0TCRGiKu9IIwehAHXOPA+OaPS+AqqaGhYk4wdyJGiwWj2T5f0aEor/chssf6fpNaNANUqv7zQjE1OTM2NjE2MzcyMjE=

{
  "startTime": "2020-07-02T00:00:00.000Z",
  "endTime": "2020-09-02T00:00:00.000Z",
  "entranceList": [
    "8946d6a8e49f4af7bdf0416f9a055e64"
  ],
  "entranceType": 1,
  "eventType": "266242",
  "statisticType": 1,
  "needSubTime": 1,
  "pageNum": 1,
  "pageSize": 20

}

### 查询通道月/年统计数据
POST http://10.6.121.29:8080/sddp/api/v1/event/statistic/statistic/query
Content-Type: application/json
Token: ECACAAAQAABaEAi5NzeX0u2i3sVNM1cKraVApw1yKj9n0TCRGiKu9IIwehAHXOPA+OaPS+AqqaGhYk4wdyJGiwWj2T5f0aEor/chssf6fpNaNANUqv7zQjE1OTM2NjE2MzcyMjE=

{
  "startTime": "2020-05-28T00:00:00.000Z",
  "endTime": "2020-11-02T00:00:00.000Z",
  "entranceList": [
    "8946d6a8e49f4af7bdf0416f9a055e64"
  ],
  "entranceType": 1,
  "eventType": "266242",
  "statisticType": 3,
  "needSubTime": 1,
  "pageNum": 1,
  "pageSize": 20

}

###

### 查询温度信息
POST http://localhost:8877/sddps/v1/parameterconfig/query
Content-Type: application/json
Token: ECACAAAQAAAhS6rXNWFjrawAzdC3v4QVws+dv0QA+Mjtn8mc7bUOEW5j4nFo4IzE+MiZNckNravCm4BN+e2+3Lw/1+qAGi7e5BTtvDHe1FGJ3iwJavHM+zE1OTQ3OTM1MTczMjk=

[
  "faceTemperature"
]

### 新增温度配置
POST http://localhost:8877/sddps/v1/parameterconfig
Content-Type: application/json
Token: ECACAAAQAAAhS6rXNWFjrawAzdC3v4QVws+dv0QA+Mjtn8mc7bUOEW5j4nFo4IzE+MiZNckNravCm4BN+e2+3Lw/1+qAGi7e5BTtvDHe1FGJ3iwJavHM+zE1OTQ3OTM1MTczMjk=

{
  "parameterName": "faceTemperature" ,
  "parameterValue": "120"
}

### 关联：安检机-安检门
POST http://localhost:8877/sdac/sddps/v1/relateDevice
Content-Type: application/json
Token: ECACAAAQAADE94531FtuxQTtRfMVDEAl112xhAtamlSzi8oB7XGnkjmDGQmYRfYq4lMcUNjzbBltyjQaFebgvl1H8OlZvYnTJUuPqhVLvJMd0xs+kQXArTE1OTQ4MTg1MjU3NDI=

{
  "parentIndexCode": "p12" ,
  "childIndexCodes": [
    "c11223" ,
    "c22" ,
    "c33"
  ]
}

### 人包匹配查询
POST http://10.6.121.29:8877/sdac/sddps/v1/face/query
Content-Type: application/json
Token: ECACAAAQAAAhS6rXNWFjrawAzdC3v4QVws+dv0QA+Mjtn8mc7bUOEW5j4nFo4IzE+MiZNckNravCm4BN+e2+3Lw/1+qAGi7e5BTtvDHe1FGJ3iwJavHM+zE1OTQ3OTM1MTczMjk=

{
  "startTime": "2020-07-10 15:22:08" ,
  "endTime": "2020-07-10 16:01:29" ,
  "curTime": "2020-07-10 15:22:44" ,
  "indexCode": "07e453c545844bbcae32b2d6802c27f9"
}

### 配置变更-更新温度
POST http://10.6.121.29:8877/sdac/sddps/v1/parameterconfig/update
Content-Type: application/json
Token: ECACAAAQAAAhS6rXNWFjrawAzdC3v4QVws+dv0QA+Mjtn8mc7bUOEW5j4nFo4IzE+MiZNckNravCm4BN+e2+3Lw/1+qAGi7e5BTtvDHe1FGJ3iwJavHM+zE1OTQ3OTM1MTczMjk=

{
  "parameterName": "faceTemperatureConfig" ,
  "parameterValue": "120"
}

### 温度查询
POST http://10.6.121.29:8877/sdac/sddps/v1/siDoor/image/query
Content-Type: application/json
Token: ECACAAAQAAAhS6rXNWFjrawAzdC3v4QVws+dv0QA+Mjtn8mc7bUOEW5j4nFo4IzE+MiZNckNravCm4BN+e2+3Lw/1+qAGi7e5BTtvDHe1FGJ3iwJavHM+zE1OTQ3OTM1MTczMjk=

{
  "startTime": "2020-07-16 15:58:03" ,
  "endTime": "2020-07-16 16:00:15" ,
  "indexCode": [
    "e89ed26ccad54fe78ff9eb605c671f1a"
  ] ,
  "pageNo": 1 ,
  "pageSize": 20 ,
  "resourceType": "sidoor"
}

### 安检门人流查询
POST http://10.6.121.29:8877/sdac/sddps/v1/details/siDoor/query
Content-Type: application/json
Token: ECACAAAQAAAhS6rXNWFjrawAzdC3v4QVws+dv0QA+Mjtn8mc7bUOEW5j4nFo4IzE+MiZNckNravCm4BN+e2+3Lw/1+qAGi7e5BTtvDHe1FGJ3iwJavHM+zE1OTQ3OTM1MTczMjk=

{
  "indexCode": "70059c94554b468186fa78c833caa797"
}

### 安检门人流查询
POST http://10.6.121.29:8877/sdac/sddps/v1/statistic/query
Content-Type: application/json
Token: ECACAAAQAAAhS6rXNWFjrawAzdC3v4QVws+dv0QA+Mjtn8mc7bUOEW5j4nFo4IzE+MiZNckNravCm4BN+e2+3Lw/1+qAGi7e5BTtvDHe1FGJ3iwJavHM+zE1OTQ3OTM1MTczMjk=

{
  "startTime": "2020-07-17 00:00:00" ,
  "endTime": "2020-07-18 00:00:00" ,
  "indexCode": [
    "70059c94554b468186fa78c833caa797"
  ] ,
  "staticType": "0" ,
  "type": null ,
  "scopeType": "0"
}

### 人数统计
POST http://10.6.121.29:8877/sdac/sddps/v1/person/totalStatistic/query
Content-Type: application/json
Token: ECACAAAQAAAhS6rXNWFjrawAzdC3v4QVws+dv0QA+Mjtn8mc7bUOEW5j4nFo4IzE+MiZNckNravCm4BN+e2+3Lw/1+qAGi7e5BTtvDHe1FGJ3iwJavHM+zE1OTQ3OTM1MTczMjk=

{
  "statisticType": "0"
}

### 人数统计
GET http://10.6.121.29:8080/sddp/api/local
Token: ECACAAAQAAC1Ptdz3CfjUunFJ7YlVnkDdc+C5pgh2MJGcEJXchIJUUufTxAHS9B5kMaIyG3Tb9QmRpPF7RGmBu4aQdeMYW5Sgc21RbZyHYXvTZt/s2+e6jE1OTUzODY2NDY3NjU=

### 查询通道天/周统计数据
POST http://10.6.121.29:8080/sddp/api/v1/event/statistic/statistic/query
Content-Type: application/json
Token: ECACAAAQAABaEAi5NzeX0u2i3sVNM1cKraVApw1yKj9n0TCRGiKu9IIwehAHXOPA+OaPS+AqqaGhYk4wdyJGiwWj2T5f0aEor/chssf6fpNaNANUqv7zQjE1OTM2NjE2MzcyMjE=

{
  "startTime": "2020-07-27T00:00:00.000Z",
  "endTime": "2020-07-30T00:00:00.000Z",
  "entranceList": [
    "629ca7da71f44e3a8a57f663773cb55d"
  ],
  "entranceType": 1,
  "eventType": "266241",
  "statisticType": 1,
  "needSubTime": 1,
  "pageNum": 1,
  "pageSize": 20

}

### 人数统计
POST http://10.6.121.29:8080/sddp/api/v1/event/dangerous/list
Content-Type: application/json
Token: ECACAAAQAABoZ+iXKvrA2pTzry5YJcrjwmXeFmnO82s8oFZQqAhoe08R22toufZNOA3gic5TxUoV0aJyyHhpIo0g4D/tShDFw4JnsCfKg2Al/1BREPm6lzE1OTYwMDYxNDY4ODU=

{
  "endTime": "2020-07-30 00:00:00",
  "entranceType": 0,
  "eventTypeList": ["45885698306"],
  "limit": 100,
  "startTime": "2020-07-16 00:00:00",
  "toAfter": false
}

###
